### ISSUE TITLE
Korean doesn't show up properly

### ISSUE THREAD

**Issue by deansgit** [ACSPRI/queXML#1]
I generated files using LimeSurvey's export function. The pdf that came out was wonky so I tried using the generated quexml file with quexmltool. It created the same error. All characters show up as boxed question marks in Adobe Acrobat Reader DC and in Chrome's native PDF reader. This happens with or without selecting embedded fonts.

[quexmlpdf_863599_en.zip](https://github.com/ACSPRI/queXML/files/4008936/quexmlpdf_863599_en.zip)

![image](https://user-images.githubusercontent.com/8883476/71567809-242d4980-2b05-11ea-9670-f1b991c1e995.png)

**Comment by adamzammit** [comment]
Hi @deansgit 

Thanks for reporting this.

I have made the following commit to queXML here: https://github.com/ACSPRI/queXML/commit/6b61c4ef5d9035c27b3bfde2cfbadc6f3652d906

Which supports setting a default font. If you choose the default font "cid0kr" then it will work - please try this on the quexmltools website: https://quexmltools.acspri.org.au/quexml/

I'll also look in to getting this working in LimeSurvey too.

Adam
